export const transactions = [
  {
    date: "06/07/2025",
    amount: 153.25,
    description: "Online Subscription",
    category: "Subscriptions",
    type: "expense",
  },
  {
    date: "03/17/2025",
    amount: 512.98,
    description: "Salary Deposit",
    category: "Work",
    type: "income",
  },
  {
    date: "04/09/2025",
    amount: 78.5,
    description: "Movie Tickets",
    category: "Entertainment",
    type: "expense",
  },
  {
    date: "09/16/2024",
    amount: 921.15,
    description: "Investment Dividend",
    category: "Investments",
    type: "income",
  },
  {
    date: "01/22/2025",
    amount: 45.75,
    description: "Coffee",
    category: "Dining",
    type: "expense",
  },
  {
    date: "02/03/2025",
    amount: 120.0,
    description: "Freelance Work",
    category: "Work",
    type: "income",
  },
  {
    date: "12/05/2024",
    amount: 320.6,
    description: "Grocery Shopping",
    category: "Food",
    type: "expense",
  },
  {
    date: "05/28/2025",
    amount: 87.2,
    description: "Gift",
    category: "Gifts",
    type: "income",
  },
  {
    date: "07/11/2024",
    amount: 65.3,
    description: "Gas Refill",
    category: "Transport",
    type: "expense",
  },
  {
    date: "10/02/2024",
    amount: 250.0,
    description: "Bonus Payment",
    category: "Work",
    type: "income",
  },
  {
    date: "08/19/2024",
    amount: 180.99,
    description: "Clothes Shopping",
    category: "Shopping",
    type: "expense",
  },
  {
    date: "03/01/2025",
    amount: 400.0,
    description: "Consulting Fee",
    category: "Business",
    type: "income",
  },
  {
    date: "01/15/2025",
    amount: 95.4,
    description: "Dinner Out",
    category: "Dining",
    type: "expense",
  },
  {
    date: "04/25/2025",
    amount: 30.1,
    description: "Interest Earned",
    category: "Investments",
    type: "income",
  },
  {
    date: "11/08/2024",
    amount: 75.0,
    description: "Gym Membership",
    category: "Health",
    type: "expense",
  },
  {
    date: "02/14/2025",
    amount: 550.0,
    description: "Rental Income",
    category: "Business",
    type: "income",
  },
  {
    date: "05/01/2025",
    amount: 110.25,
    description: "Utility Bill",
    category: "Utilities",
    type: "expense",
  },
  {
    date: "09/03/2024",
    amount: 60.5,
    description: "Refund",
    category: "Refunds",
    type: "income",
  },
  {
    date: "10/20/2024",
    amount: 40.0,
    description: "Public Transport",
    category: "Transport",
    type: "expense",
  },
  {
    date: "06/15/2025",
    amount: 700.0,
    description: "Side Hustle Income",
    category: "Other Income",
    type: "income",
  },
];
